# Generated by Django 4.2.28 on 2026-04-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this account', max_length=255)),
                ('instagram_user_id', models.CharField(help_text='Instagram User ID (numeric)', max_length=100, unique=True)),
                ('app_id', models.CharField(help_text='Meta App ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Meta App Secret', max_length=255)),
                ('access_token', models.TextField(blank=True, default='', help_text='Current long-lived access token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the token expires', null=True)),
                ('token_last_refreshed', models.DateTimeField(blank=True, help_text='Last token refresh time', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('IMAGE', 'Image'), ('REEL', 'Reel')], default='IMAGE', max_length=10)),
                ('caption', models.TextField(blank=True, default='', help_text='Post caption/description')),
                ('media_file', models.FileField(blank=True, help_text='Upload image (JPEG) or video (MP4/MOV)', null=True, upload_to='posts/media/%Y/%m/')),
                ('media_url', models.URLField(blank=True, default='', help_text='Or provide a public URL to the media', max_length=2000)),
                ('thumbnail_file', models.FileField(blank=True, help_text='Upload reel cover/thumbnail image (JPEG)', null=True, upload_to='posts/thumbnails/%Y/%m/')),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Or provide a public URL to the thumbnail', max_length=2000)),
                ('scheduled_time', models.DateTimeField(help_text='When to publish this post')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('ig_container_id', models.CharField(blank=True, default='', help_text='Instagram container ID from API', max_length=100)),
                ('ig_media_id', models.CharField(blank=True, default='', help_text='Published Instagram media ID', max_length=100)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if publishing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.instagramaccount')),
            ],
            options={
                'verbose_name': 'Scheduled Post',
                'verbose_name_plural': 'Scheduled Posts',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
