# Generated by Django 4.2.28 on 2026-04-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='instagram_user_id',
            field=models.CharField(blank=True, default='', help_text='Instagram User ID (auto-detected from token)', max_length=100),
        ),
    ]
