# Generated by Django 4.2.28 on 2026-04-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_instagramaccount_instagram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='YouTube Channel Name', max_length=255)),
                ('channel_id', models.CharField(help_text='YouTube Channel ID', max_length=100, unique=True)),
                ('access_token', models.TextField(blank=True, default='', help_text='Current OAuth2 access token')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth2 refresh token (long-lived)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Channel thumbnail / avatar URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Account',
                'verbose_name_plural': 'YouTube Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube')], default='INSTAGRAM', help_text='Target platform for this post', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Video title (required for YouTube)', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='yt_video_id',
            field=models.CharField(blank=True, default='', help_text='Uploaded YouTube video ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.instagramaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='youtube_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.youtubeaccount'),
        ),
    ]
