# Generated by Django 4.2.28 on 2026-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_youtubeaccount_scheduledpost_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='yt_category_id',
            field=models.CharField(default='22', help_text='YouTube Category ID (e.g. 22 for People & Blogs)', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='yt_made_for_kids',
            field=models.BooleanField(default=False, help_text='Is this video made for kids?'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='yt_privacy_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', help_text='Privacy status for YouTube', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='yt_tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags for YouTube', max_length=500),
        ),
    ]
