# Generated by Django 4.2.28 on 2026-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_scheduledpost_yt_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', help_text='Instagram Profile Picture URL', max_length=500),
        ),
    ]
