# Generated by Django 4.2.30 on 2026-06-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0005_instagramaccount_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='youtubeaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
