# Generated by Django 4.2.30 on 2026-06-26 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0007_associate_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('X', 'X (Twitter)'), ('FACEBOOK', 'Facebook Page'), ('PINTEREST', 'Pinterest'), ('TIKTOK', 'TikTok')], default='INSTAGRAM', help_text='Target platform for this post', max_length=15),
        ),
        migrations.CreateModel(
            name='XAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='X Account Name', max_length=255)),
                ('screen_name', models.CharField(help_text='X Handle / @username', max_length=100, unique=True)),
                ('access_token', models.TextField(blank=True, default='', help_text='OAuth2 access token')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth2 refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, default='', help_text='Avatar URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'X Account',
                'verbose_name_plural': 'X Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='TikTok Display Name', max_length=255)),
                ('username', models.CharField(help_text='TikTok @username', max_length=100, unique=True)),
                ('access_token', models.TextField(blank=True, default='', help_text='TikTok access token')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='TikTok refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, default='', help_text='Avatar URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TikTok Account',
                'verbose_name_plural': 'TikTok Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinterestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pinterest Username', max_length=255)),
                ('board_name', models.CharField(help_text='Pinterest Board Name', max_length=255)),
                ('access_token', models.TextField(blank=True, default='', help_text='Pinterest access token')),
                ('profile_picture_url', models.URLField(blank=True, default='', help_text='Profile picture URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinterest_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinterest Account',
                'verbose_name_plural': 'Pinterest Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Facebook Page Name', max_length=255)),
                ('page_id', models.CharField(help_text='Facebook Page ID', max_length=100, unique=True)),
                ('access_token', models.TextField(blank=True, default='', help_text='Page access token')),
                ('profile_picture_url', models.URLField(blank=True, default='', help_text='Page avatar URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Account',
                'verbose_name_plural': 'Facebook Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='facebook_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.facebookaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='pinterest_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.pinterestaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='tiktok_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.tiktokaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='x_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.xaccount'),
        ),
    ]
